# Generated by Django 5.2.8 on 2025-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_consultation_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Height (ft)'),
        ),
    ]
