# Generated by Django 5.2.8 on 2025-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_bed_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
