# Generated by Django 5.2.8 on 2025-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Compounder', 'Compounder'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
