# Generated by Django 5.2.8 on 2025-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Compounder', 'Compounder'), ('Receptionist', 'Receptionist'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
