# Generated by Django 5.2.8 on 2025-12-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_city_state_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Neurologist', 'Neurologist'), ('The Gynecologist', 'The Gynecologist'), ('Orthopedist', 'Orthopedist'), ('Surgeon', 'Surgeon'), ('Psychiatrist', 'Psychiatrist'), ('ENT Specialist', 'ENT Specialist'), ('Ophthalmologist', 'Ophthalmologist'), ('Dentist', 'Dentist')], default='General Physician', max_length=100),
        ),
    ]
