# Generated by Django 5.2.8 on 2025-12-10 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('bp_systolic', models.IntegerField(help_text='Systolic Blood Pressure (mmHg)')),
                ('bp_diastolic', models.IntegerField(help_text='Diastolic Blood Pressure (mmHg)')),
                ('heart_rate', models.IntegerField(help_text='Heart Rate (bpm)')),
                ('temperature', models.FloatField(help_text='Temperature (Celsius)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
