# Generated by Django 5.2.8 on 2025-12-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hospitals', '0007_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to='hospitals.hospital'),
        ),
    ]
